Mkhadiv/bolt humanoid
open-dynamic-robot-initiative/robot_properties_bolt pull request #10
Opened 2021-12-02 17:09 UTC by majidkhadiv

[//]: # "Thanks for your contribution.  To make life of the reviewers easier,"
[//]: # "please give this pull request a meaningful title and provide the"
[//]: # "requested information below."

## Description
I created urdf for the bolt humanoid on top of bolt urdf. The new robot has one rotational DOF in waist and two DOFs per shoulder in flexion/extension direction

## How I Tested

[//]: # "Explain how you tested your changes"
I created the same demos for the BoltHumanoid as the ones for Bolt. All the demos should be working fine.

2021-12-03 15:50 UTC, jviereck requested changes
Small request for changes / discussion. Overall, this looks very good. Thanks for adding this!

2021-12-03 15:50 UTC, jviereck commented on demos/demo_display_bolt_humanoid_meshcat.py
> +viz = pin.visualize.MeshcatVisualizer(
Should this code and the following be indented under the `if __name__ == "__main__"` statement as well?

2021-12-03 15:50 UTC, jviereck commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        self.is_passive=is_passive
What does "passive" mean for the robot?

2021-12-03 15:50 UTC, jviereck commented on src/robot_properties_bolt/resources/dynamic_graph_manager/dgm_parameters_bolt_humanoid.yaml
> +    base_accelerometer:
As discussed yesterday, please call the signal `imu_accelerometer`. Same for the other `base_*` signals.

2021-12-03 15:50 UTC, jviereck commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        for arm in ["L", "R"]:
Should we call the arm joints `TL` and `TR` for "top"? We use the prefix `F` as in  `FL` and `FR` as well. Not having strong feelings on this.

2021-12-03 15:51 UTC, jviereck requested changes
Overall, this looks quite good. A few small changes than this is good to merge.

Thanks for adding thi!

2021-12-03 15:51 UTC, jviereck commented
+\cc @avadesh02 as he might be interested in this as well

2021-12-05 16:09 UTC, MaximilienNaveau requested changes
Overall I agree with @jviereck on the small changes to be made.

2021-12-05 16:09 UTC, MaximilienNaveau commented on demos/demo_display_bolt_humanoid_meshcat.py
> +viz = pin.visualize.MeshcatVisualizer(
+1

2021-12-05 16:09 UTC, MaximilienNaveau commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        self.is_passive=is_passive
I think it's passive ankle modeling

2021-12-05 16:09 UTC, MaximilienNaveau commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        self.is_passive=is_passive
opposite to point feet

2021-12-05 16:09 UTC, MaximilienNaveau commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        for arm in ["L", "R"]:
or "AL" "AR" like 'arm'

2021-12-10 13:49 UTC, majidkhadiv commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        self.is_passive=is_passive
Yes, this is if you wanna also simulate passive ankle later

2021-12-10 13:52 UTC, majidkhadiv commented on src/robot_properties_bolt/bolt_humanoid_wrapper.py
> +        for arm in ["L", "R"]:
but in FL and FR, F stands for front and we do not have sth like front and hind for arms...

2021-12-10 13:54 UTC, merged